### ISSUE TITLE
Incompatible with Django 3

### ISSUE THREAD

**Issue by Urahara** [cuducos/django-public-admin#16]
When i try to install `poetry install` with the **pyproject.toml** above:

```toml
[tool.poetry]
name = "poeta"
version = "0.1.0"
description = ""
authors = ["Urahara"]

[tool.poetry.dependencies]
python = "^3.6"
django = "3.0.8"
django-public-admin = "^0.0.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

Result:
```sh
Updating dependencies
Resolving dependencies... (0.4s)

[SolverProblemError]
Because no versions of django-public-admin match >0.0.2,<0.0.3
 and django-public-admin (0.0.2) depends on django (>=2.0.0,<3.0.0), django-public-admin (>=0.0.2,<0.0.3) requires django (>=2.0.0,<3.0.0).
So, because poeta depends on both django (3.0.8) and django-public-admin (^0.0.2), version solving failed.
```

Slightly modifying to use the latest 2.x release of django i able to use without problems:

```toml
[tool.poetry]
name = "poeta"
version = "0.1.0"
description = ""
authors = ["Urahara"]

[tool.poetry.dependencies]
python = "^3.6"
django = "2.2.14"
django-public-admin = "^0.0.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

Result:
```sh
Updating dependencies
Resolving dependencies... (2.8s)

Writing lock file


Package operations: 4 installs, 0 updates, 0 removals

  - Installing pytz (2020.1)
  - Installing sqlparse (0.3.1)
  - Installing django (2.2.14)
  - Installing django-public-admin (0.0.2)
```
